DECLARE  @IDPROC INT
		, @CODPL VARCHAR(10)
		, @CODCOLIGADA INT
		, @CODCFO VARCHAR(25)
		, @IDCFO INT
		, @NOMEFANTASIA VARCHAR(100)
		, @NOME VARCHAR(100)
		, @PESSOAFISOUJUR VARCHAR(1)
		, @PAGREC INT
		, @CEP INT
		, @RUA VARCHAR(100)
		, @NUMERO VARCHAR(8)
		, @COMPLEMENTO VARCHAR(60)
		, @BAIRRO VARCHAR(80)
		, @CODETD VARCHAR(2)
		, @TELEFONE VARCHAR(15)
		, @CGCCFO VARCHAR(20)
		, @CODMUNICIPIO VARCHAR(20)
		, @ULTIMO_CFO VARCHAR(25)
		, @ULTIMO_IDCFO INT
		, @USUARIO VARCHAR(50)
		, @ATIVO INT
		, @DTIMPORT DATE
		, @RAMOATIV INT
		, @TIPOCONTRIBUINTE INT
		, @NACIONALIDADE INT
		, @CALCULAAVP INT
		, @ENTIDADEEXECUTORAPAA INT
		, @APOSENTADOOUPENSIONISTA INT
		, @ID INT
		, @NUMEROINSCPROCSEL VARCHAR(10)
		, @NOME_ALUNO VARCHAR(120)
		, @SEXO_ALUNO VARCHAR(1)
		, @DATANASC DATE
		--, CIDADE AS CIDADENASC
		--, ESTADO AS UFNASC
		, @PAI VARCHAR(45)
		, @MAE VARCHAR(45)
		, @CPFFIADOR VARCHAR(11)
		, @IDENT VARCHAR(15)
		, @CPFALUNO VARCHAR(11)
		, @LOGRADOURO_ALUNO VARCHAR(100)
		, @COMPLEMENTO_ALUNO VARCHAR(60)
		, @NUMEROIMOVEL VARCHAR(6)
		, @BAIRRO_ALUNO VARCHAR(80)
		, @CIDADE_ALUNO VARCHAR(32)
		, @ESTADO_ALUNO VARCHAR(2)
		, @CEP_ALUNO VARCHAR(9)
		, @TELEFONE_ALUNO VARCHAR(45)
		, @IDOPORTUNIDADE_CRM VARCHAR(255)
		, @CURSO VARCHAR(60)
		, @PONTUACAO NUMERIC(15,4)
		, @CODCURSO VARCHAR(3)
		, @CODTIPOCURSO INT
		, @IDHABILITACAOFILIAL INT
		, @IDPERLET INT
		, @PERIODO INT
		, @OPCAO INT
		, @IDPROCSEL INT
		, @IDLAN INT
		, @NUMERODOCUMENTO VARCHAR(40)
		, @IDBAIXA INT
		, @IDTRANSACAO INT
		, @IDXCX INT
		, @PGTONLINE INT
		, @NFOUDUP INT
		, @CLASSIFICACAO INT
		, @PAGREC_LAN INT
		, @STATUSLAN INT
		, @DATAVENCIMENTO DATE
		, @DATAEMISSAO DATE
		, @VALORORIGINAL NUMERIC(10,2)
		, @VALORBAIXADO NUMERIC(10,2)
		, @VALORCAP NUMERIC(10,2)
		, @VALORJUROS NUMERIC(10,2)
		, @VALORDESCONTO NUMERIC(10,2)
		, @VALOROP1 NUMERIC(10,2)
		, @VALOROP2 NUMERIC(10,2)
		, @VALOROP3 NUMERIC(10,2)
		, @VALOROP4 NUMERIC(10,2)
		, @VALOROP5 NUMERIC(10,2)
		, @VALOROP6 NUMERIC(10,2)
		, @VALOROP7 NUMERIC(10,2)
		, @VALOROP8 NUMERIC(10,2)
		, @VALORMULTA NUMERIC(10,2)
		, @VALORADIANTAMENTO NUMERIC(10,2)
		, @VALORDEVOLUCAO NUMERIC(10,2)
		, @JUROSDIA NUMERIC(10,2)
		, @CODCOLCFO INT
		, @CODCFO_LAN VARCHAR(25)
		, @CODCOLCXA INT
		, @CODCXA VARCHAR(10)
		, @CODTDO VARCHAR(10)
		, @CODFILIAL_LAN INT
		, @TIPOCONTABILLAN INT
		, @STATUSEXPORTACAO INT
		, @NUMLOTECONTABIL INT
		, @STATUSEXTRATO INT
		, @CNABSTATUS INT
		, @REEMBOLSAVEL INT
		, @BAIXAAUTORIZADA INT
		, @TEMCHEQUEPARCIAL INT
		, @JAIMPRIMIU INT
		, @NUMBLOQUEIOS INT
		, @TIPOJUROSDIA INT
		, @ALTERACAOBLOQUEADA INT
		, @MULTADIA  NUMERIC(10,2)
		, @DESCONTADO INT
		, @VALORINSS  NUMERIC(10,2)
		, @VALORIRRF NUMERIC(10,2)
		, @VALORDEDUCAO  NUMERIC(10,2)
		, @INSSEMOUTRAEMPRESA  NUMERIC(10,2)
		, @PERCENTBASEINSS  NUMERIC(10,2)
		, @PERCBASEINSSEMPREGADO  NUMERIC(10,2)
		, @IMPOSTOEDITADO INT
		, @REUTILIZACAO INT
		, @VALORSESTSENAT  NUMERIC(10,2)
		, @VRPERDAFINANCEIRA  NUMERIC(10,2)
		, @STATUSDDA INT
		, @STATUSAVP INT
		, @VALORORIGINALBX  NUMERIC(10,2)
		, @VALORDESCONTOBX  NUMERIC(10,2)
		, @VALORMULTABX  NUMERIC(10,2)
		, @VALORCAPBX  NUMERIC(10,2)
		, @VALOROP1BX  NUMERIC(10,2)
		, @VALOROP2BX  NUMERIC(10,2)
		, @VALOROP3BX  NUMERIC(10,2)
		, @VALOROP4BX  NUMERIC(10,2)
		, @VALOROP5BX  NUMERIC(10,2)
		, @VALOROP6BX  NUMERIC(10,2)
		, @VALOROP7BX  NUMERIC(10,2)
		, @VALOROP8BX  NUMERIC(10,2)
		, @VALORINSSBX  NUMERIC(10,2)
		, @VALORIRRFBX  NUMERIC(10,2)
		, @VALORSESTSENATBX  NUMERIC(10,2)
		, @VALORDEVOLUCAOBX  NUMERIC(10,2)
		, @VALORNOTACREDITOBX  NUMERIC(10,2)
		, @VALORADIANTAMENTOBX  NUMERIC(10,2)
		, @VALORJUROSVENDORBX  NUMERIC(10,2)
		, @VALORRETENCOESBX  NUMERIC(10,2)
		, @VALORPERDAFINANCEIRABX  NUMERIC(10,2)
		, @VALORVINCULADO  NUMERIC(10,2)
		, @MODELOCONTABILIZACAO INT
		, @MODELOCONTABILIZACAOBAIXA INT
		, @VALORDESCONTODUPLICATA  NUMERIC(10,2)
		, @VALORDESCONTOACORDO  NUMERIC(10,2)
		, @VALORACRESCIMOACORDO  NUMERIC(10,2)
		, @STATUSORCAMENTO INT
		, @VALORDESCONTOPONTUALBX  NUMERIC(10,2)
		, @HISTORICO VARCHAR(255)
		, @CODMOEDA VARCHAR(10)
		, @CODAPLICACAO VARCHAR(1)
		, @SERIEDOCUMENTO VARCHAR(8)
		, @VALORBAIXA  NUMERIC(10,2)
		, @DATABAIXA DATE 
		, @VALORNOTACREDITO NUMERIC(10,2)
		, @VALORNOTACREDITOADIANTAMENTO NUMERIC(10,2)
		, @VALORJUROSVENDOR NUMERIC(10,2)
		, @VALORRETENCOES NUMERIC(10,2)
		, @VALORPERDAFINANCEIRA NUMERIC(10,2)
		, @VALORJUROSACORDO NUMERIC(10,2)
		, @TIPOBAIXA INT
		, @STATUS INT
		, @DIFBAIXAPARCIAL INT
		, @TIPORETORNOBANCARIO INT
		, @ORIGEMVALORDESCONTO INT
		, @ORIGEMVALORJUROS INT
		, @ORIGEMVALORMULTA INT
		, @ORIGEMVALORCAP INT
		, @ORIGEMVALOROP1 INT
		, @ORIGEMVALOROP2 INT
		, @ORIGEMVALOROP3 INT
		, @ORIGEMVALOROP4 INT
		, @ORIGEMVALOROP5 INT
		, @ORIGEMVALOROP6 INT
		, @ORIGEMVALOROP7 INT
		, @ORIGEMVALOROP8 INT
		, @VALORDESCONTOPONTUAL INT
		, @DTVENCIMENTOLCTO DATE
		, @IDFORMAPAGTO INT
		, @TIPO INT
		, @COMPENSADO INT
		, @RECONCILIADO INT
		, @CODCOLFXCX INT
		, @VALOR NUMERIC(10,2)
		, @DATA DATE
		, @CONTABIL INT
		, @ECHEQUE INT
		, @TIPOCUSTODIA INT
		, @LIBERACAOAUTORIZADA INT
		, @CODFILIAL INT;


SET @CODPL = '2020S1';
SET @IDPROC = (SELECT DISTINCT IDPROCSEL FROM SPROCSEL WHERE CODPROCSEL = @CODPL);


IF OBJECT_ID('tempdb..#Temp_CliforCRM') is not null
       BEGIN
             drop table #Temp_CliforCRM
       END;


SELECT DISTINCT 1 AS CODCOLIGADA
				, UPPER(NOMERESPONSAVEL) AS NOMEFANTASIA
				, UPPER(NOMERESPONSAVEL) AS NOME
				, LOGRADOURO AS RUA
				, BAIRRO AS BAIRRO
				, (SELECT DISTINCT TOP 1 CODMUNICIPIO FROM GMUNICIPIO WHERE NOMEMUNICIPIO = student.CIDADE) AS CODMUNICIPIO
				, ESTADO AS UF
				, CEP AS  CEP
				, TELEFONE AS TELEFONE
				, EMAIL AS EMAIL
				, REPLACE(REPLACE(CPFRESPONSAVEL,'.',''),'-','') AS CGCCFO
				, 'F' AS PESSOAFISOUJUR
				, COMPLEMENTO AS COMPLEMENTO
				, NUMEROIMOVEL AS NUMERO
				, 3 AS PAGREC
				, 'crm' AS USUARIO
				, GETDATE() AS DTIMPORT
				, ID AS ID
				, PGTONLINE AS PGTONLINE


INTO #Temp_CliforCRM
FROM [172.16.254.42].salesforce.dbo.students student;


IF OBJECT_ID('tempdb..#Temp_CandidatoCRM') is not null
       BEGIN
             drop table #Temp_CandidatoCRM
       END;

SELECT DISTINCT 1 AS CODCOLIGADA
				, @IDPROC AS IDPROCSEL
				, ID+1000 AS NUMEROINSCPROCSEL
				, UPPER(student.NOME) AS NOME
				, CASE WHEN SEXO = 'Masculino' THEN 'M' ELSE 'F' END AS SEXO
				, DATANASC AS DATANASC
				--, CIDADE AS CIDADENASC
				--, ESTADO AS UFNASC
				, NOMEPAI AS PAI
				, NOMEMAE AS MAE
				, CPFRESPONSAVEL AS CPFFIADOR
				, IDENT AS IDENT
				, CPFALUNO AS CPFALUNO
				, LOGRADOURO AS LOGRADOURO
				, COMPLEMENTO AS COMPLEMENTO
				, NUMEROIMOVEL AS NUMEROIMOVEL
				, BAIRRO AS BAIRRO
				, CIDADE AS CIDADE
				, ESTADO AS ESTADO
				, CEP AS CEP
				, TELEFONE AS TELEFONE
				, 'crm' AS USUARIO
				, GETDATE() AS DTIMPORT
				, NUMEROINSCPROCSEL AS IDOPORTUNIDADE_CRM
				, CURSO1 AS CURSO
				, PONTUACAO1 AS PONTUACAO
				, CASE ST.NOME 
					   WHEN 'Manhã' THEN LEFT(student.CODCURSO,2)+'M' 
					   WHEN 'Integral' THEN LEFT(student.CODCURSO,2)+'M'
					   WHEN 'Noite' THEN LEFT(student.CODCURSO,2)+'N'
				  END
					   AS CODCURSO
				, student.CODTIPOCURSO AS CODTIPOCURSO
				, student.IDHABILITACAOFILIAL AS IDHABILITACAOFILIAL
				, PERIODO AS PERIODO
				, 1 AS OPCAO
				, CAST(student.VALORINSCRICAO AS numeric(10,2)) AS VALORINSCRICAO
				, NATURALIDADE AS NATURALIDADE


INTO #Temp_CandidatoCRM
FROM [172.16.254.42].salesforce.dbo.students student JOIN SHABILITACAOFILIAL SHF WITH (NOLOCK) ON SHF.IDHABILITACAOFILIAL = student.IDHABILITACAOFILIAL
													 JOIN STURNO ST WITH (NOLOCK) ON ST.CODCOLIGADA = SHF.CODCOLIGADA AND ST.CODTURNO = SHF.CODTURNO AND ST.CODTIPOCURSO = SHF.CODTIPOCURSO;



IF OBJECT_ID('tempdb..#Temp_CursoCandidatoCRM') is not null
       BEGIN
             drop table #Temp_CursoCandidatoCRM
       END;


SELECT DISTINCT 1 AS CODCOLIGADA
				, (SELECT DISTINCT IDPERLET FROM SPLETIVO WHERE CODPERLET = @CODPL AND CODTIPOCURSO = student.CODTIPOCURSO) AS IDPERLET
				, @IDPROC AS IDPROCSEL
				, NUMEROINSCPROCSEL AS NUMEROINSCPROCSEL
				, CODCURSO AS CODCURSO
				, OPCAO AS OPCAO
				, PONTUACAO AS PONTUACAO
				, IDHABILITACAOFILIAL AS IDHABILITACAOFILIAL
				, USUARIO AS RECCREATEDBY
				, DTIMPORT AS RECCREATEDON
				, USUARIO AS RECMODIFIEDBY
				, DTIMPORT AS RECMODIFIEDON 

INTO #Temp_CursoCandidatoCRM
FROM #Temp_CandidatoCRM student;


IF OBJECT_ID('tempdb..#Temp_Adiantamento') is not null
       BEGIN
             drop table #Temp_Adiantamento
       END;

SELECT DISTINCT #Temp_CliforCRM.CODCOLIGADA AS CODCOLIGADA
				, #Temp_CliforCRM.CGCCFO
				--, (SELECT MAX(VALAUTOINC) FROM GAUTOINC WITH (NOLOCK) WHERE NOMETABELA = 'FLAN' AND NOMECOLUNA = 'IDLAN' AND CODCOLIGADA = 1 AND CODSISTEMA = 'F' AND CODAUTOINC = 'IDLAN')
				--, (SELECT MAX(VALAUTOINC) FROM GAUTOINC WITH (NOLOCK) WHERE NOMETABELA = 'FLAN' AND NOMECOLUNA = 'IDLAN' AND CODCOLIGADA = 1 AND CODSISTEMA = 'F' AND CODAUTOINC = 'IDLAN')+ID 
				, (SELECT MAX(VALAUTOINC) FROM GAUTOINC WITH (NOLOCK) WHERE NOMETABELA = 'FLAN' AND NOMECOLUNA = 'IDLAN' AND CODCOLIGADA = 1 AND CODSISTEMA = 'F' AND CODAUTOINC = 'IDLAN')+ROW_NUMBER() OVER(ORDER BY ID ASC) AS IDLAN
				, '00000'+ CAST((SELECT MAX(VALAUTOINC) FROM GAUTOINC WITH (NOLOCK) WHERE NOMETABELA = 'FLAN' AND NOMECOLUNA = 'IDLAN' AND CODCOLIGADA = 1 AND CODSISTEMA = 'F' AND CODAUTOINC = 'IDLAN')+ROW_NUMBER() OVER(ORDER BY ID ASC) AS VARCHAR(10)) AS NUMERODOCUMENTO
				, 0 AS NFOUDUP
				, 0 AS CLASSIFICACAO
				, 1 AS PAGREC
				, 1 AS STATUSLAN
				, PAYMENTS_CRM.DTVCTO AS DATAVENCIMENTO
				, PAYMENTS_CRM.DATAEMISSAO DATAEMISSAO
				, #Temp_CandidatoCRM.VALORINSCRICAO AS VALORORIGINAL
				, 0 AS VALORBAIXADO
				, 0 AS VALORCAP
				, 0 AS VALORJUROS
				, 0 AS VALORDESCONTO
				, 0 AS VALOROP1
				, 0 AS VALOROP2
				, 0 AS VALOROP3
				, 0 AS VALOROP4
				, 0 AS VALOROP5
				, 0 AS VALOROP6
				, 0 AS VALOROP7
				, 0 AS VALOROP8
				, 0 AS VALORMULTA
				, 0 AS VALORADIANTAMENTO
				, 0 AS VALORDEVOLUCAO
				, 0 AS JUROSDIA
				, 1 AS CODCOLCFO
				, (SELECT TOP 1 CODCFO FROM FCFO WITH (NOLOCK) WHERE CGCCFO = #Temp_CliforCRM.CGCCFO AND CODCOLIGADA = #Temp_CliforCRM.CODCOLIGADA) AS CODCFO
				, 1 AS CODCOLCXA
				, CASE PAYMENTS_CRM.TIPO_PGTO
					WHEN 'boleto' THEN '8.7'
					WHEN 'credit' THEN '1.4'
					WHEN 'debit' THEN '1.5'
							END AS	CODCXA
				, '0224' AS CODTDO
				, 1 AS CODFILIAL
				, 1 AS TIPOCONTABILLAN
				, 0 AS STATUSEXPORTACAO
				, 6000 AS NUMLOTECONTABIL
				, 0 AS STATUSEXTRATO
				, 0 AS CNABSTATUS
				, 0 AS REEMBOLSAVEL
				, 1 AS BAIXAAUTORIZADA
				, 0 AS TEMCHEQUEPARCIAL
				, 0 AS JAIMPRIMIU
				, 0 AS NUMBLOQUEIOS
				, 0 AS TIPOJUROSDIA
				, 0 AS ALTERACAOBLOQUEADA
				, 0 AS MULTADIA
				, 0 AS DESCONTADO
				, 0 AS VALORINSS
				, 0 AS VALORDEDUCAO
				, 0 AS INSSEMOUTRAEMPRESA
				, 100 AS PERCENTBASEINSS
				, 100 AS PERCBASEINSSEMPREGADO
				, 0 AS IMPOSTOEDITADO
				, 0 AS REUTILIZACAO
				, 0 AS VALORSESTSENAT
				, 0 AS VRPERDAFINANCEIRA
				, 0 AS STATUSDDA
				, 0 AS STATUSAVP
				, 0 AS VALORORIGINALBX
				, 0 AS VALORDESCONTOBX
				, 0 AS VALORMULTABX
				, 0 AS VALORCAPBX
				, 0 AS VALOROP1BX
				, 0 AS VALOROP2BX
				, 0 AS VALOROP3BX
				, 0 AS VALOROP4BX
				, 0 AS VALOROP5BX
				, 0 AS VALOROP6BX
				, 0 AS VALOROP7BX
				, 0 AS VALOROP8BX
				, 0 AS VALORINSSBX
				, 0 AS VALORIRRFBX
				, 0 AS VALORSESTSENATBX
				, 0 AS VALORDEVOLUCAOBX
				, 0 AS VALORNOTACREDITOBX
				, 0 AS VALORADIANTAMENTOBX
				, 0 AS VALORJUROSVENDORBX
				, 0 AS VALORRETENCOESBX
				, 0 AS VALORPERDAFINANCEIRABX
				, 0 AS VALORVINCULADO
				, 0 AS MODELOCONTABILIZACAO
				, 0 AS MODELOCONTABILIZACAOBAIXA
				, 0 AS VALORDESCONTODUPLICATA
				, 0 AS VALORDESCONTOACORDO
				, 0 AS VALORACRESCIMOACORDO
				, 0 AS STATUSORCAMENTO
				, 0 AS VALORDESCONTOPONTUALBX
				, (SELECT MAX(VALAUTOINC) FROM GAUTOINC WHERE CODCOLIGADA = 1 AND CODSISTEMA = 'F' AND NOMECOLUNA = 'IDXCX' AND CODAUTOINC = 'IDXCX' AND NOMETABELA = 'FXCX')+ROW_NUMBER() OVER(ORDER BY ID ASC) AS IDXCX
				, (SELECT MAX(VALAUTOINC) FROM GAUTOINC WHERE CODCOLIGADA = 1 AND NOMETABELA = 'FLANBAIXA' AND CODAUTOINC = 'IDTRANSACAO' AND NOMECOLUNA = 'IDTRANSACAO' AND CODSISTEMA = 'F')+ROW_NUMBER() OVER(ORDER BY ID ASC) AS IDTRANSACAO
				, ISNULL(PAYMENTS_CRM.DATABAIXA, GETDATE()) AS DATABAIXA
				, CAST(CAST(PAYMENTS_CRM.VALORPAGO AS float)/100 AS numeric(10,2))  AS VALORBAIXA
				--, 0 AS VALORINSS
				, 0 AS VALORIRRF
				--, 0 AS VALORSESTSENAT
				--, 0 AS VALORDEVOLUCAO
				, 0 AS VALORNOTACREDITO
				, 0 AS VALORNOTACREDITOADIANTAMENTO
				, 0 AS VALORJUROSVENDOR
				, 0 AS VALORRETENCOES
				, 0 AS VALORPERDAFINANCEIRA
				, 0 AS VALORJUROSACORDO
				--, 0 AS VALORDESCONTOACORDO
				--, 0 AS VALORACRESCIMOACORDO
				, 0 AS TIPOBAIXA
				, 0 AS STATUS
				, 0 AS DIFBAIXAPARCIAL
				, 0 AS TIPORETORNOBANCARIO
				, 0 AS ORIGEMVALORDESCONTO
				, 0 AS ORIGEMVALORJUROS
				, 0 AS ORIGEMVALORMULTA
				, 0 AS ORIGEMVALORCAP
				, 0 AS ORIGEMVALOROP1
				, 0 AS ORIGEMVALOROP2
				, 0 AS ORIGEMVALOROP3
				, 0 AS ORIGEMVALOROP4
				, 0 AS ORIGEMVALOROP5
				, 0 AS ORIGEMVALOROP6
				, 0 AS ORIGEMVALOROP7
				, 0 AS ORIGEMVALOROP8
				, 0 AS VALORDESCONTOPONTUAL
				, (SELECT MAX(VALAUTOINC) FROM GAUTOINC WHERE CODCOLIGADA = 1 AND NOMETABELA = 'FLANBAIXA' AND CODAUTOINC = 'IDBAIXA' AND NOMECOLUNA = 'IDBAIXA' AND CODSISTEMA = 'F')+ROW_NUMBER() OVER(ORDER BY ID ASC) AS IDBAIXA
				, 5 AS TIPO
				, 0 AS COMPENSADO
				, 0 AS RECONCILIADO
				--, 0 AS STATUSEXPORTACAO
				, CAST(CAST(PAYMENTS_CRM.VALORPAGO AS float)/100 AS numeric(10,2))  AS VALOR
				, ISNULL(PAYMENTS_CRM.DATABAIXA, GETDATE()) AS DATA
				, 0 AS CONTABIL
				, 0 AS ECHEQUE
				, 0 AS TIPOCUSTODIA
				, 0 AS LIBERACAOAUTORIZADA
				, 'R$' AS CODMOEDA
				, '@@@' AS SERIEDOCUMENTO
				, 'F' AS CODAPLICACAO
				, 'Pagamento Ref. Matrícula Aluno: ' + #Temp_CandidatoCRM.NOME AS HISTORICO
				, 'crm' AS USUARIO
				, GETDATE() AS DTIMPORT

INTO #Temp_Adiantamento
FROM #Temp_CliforCRM 
		JOIN #Temp_CandidatoCRM ON #Temp_CandidatoCRM.CODCOLIGADA = #Temp_CliforCRM.CODCOLIGADA AND #Temp_CandidatoCRM.CPFFIADOR = #Temp_CliforCRM.CGCCFO
		JOIN [172.16.254.42].SIDE.dbo.PAYMENTS_CRM ON PAYMENTS_CRM.CPF = #Temp_CliforCRM.CGCCFO;





DECLARE zmd_cursor CURSOR FOR 
SELECT DISTINCT CODCOLIGADA AS CODCOLIGADA
		   , 'C'+CAST((SELECT CAST(RIGHT(MAX(CODCFO),7) AS int) FROM FCFO WHERE CODCFO LIKE 'C%')+ROW_NUMBER() OVER(ORDER BY ID ASC) AS varchar(25)) AS CODCFO
		   , (SELECT MAX(IDCFO) FROM FCFO WITH (NOLOCK))+ROW_NUMBER() OVER(ORDER BY ID ASC) AS IDCFO
		   --, (SELECT MAX(IDCFO) FROM FCFO WITH (NOLOCK))+1 AS IDCFO
		   , NOME AS NOME
		   , NOMEFANTASIA AS NOMEFANTASIA
		   , PESSOAFISOUJUR AS PESSOAFISOUJUR
		   , PAGREC AS PAGREC
		   , CEP AS CEP
		   , RUA AS RUA
		   , NUMERO AS NUMERO
		   , COMPLEMENTO AS COMPLEMENTO
		   , BAIRRO AS BAIRRO
		   --, IDPAIS AS IDPAIS
		   , UF AS CODETD
		   , TELEFONE AS TELEFONE
		   , CGCCFO AS CGCCFO
		   , CODMUNICIPIO AS CODMUNICIPIO
		   , (SELECT MAX(CODCFO) FROM FCFO WHERE CODCFO LIKE 'C%') AS ULTIMO_CFO
		   , (SELECT MAX(IDCFO) FROM FCFO WITH (NOLOCK)) AS ULTIMO_IDCFO
		   , 'crm' AS USUARIO
		   , GETDATE() AS DTIMPORT


    FROM
        #Temp_CliforCRM
		WHERE NOT EXISTS (SELECT CODCFO FROM ZMDFCFOCRM WHERE CGCCFO = #Temp_CliforCRM.CGCCFO)
    --WHERE NOT EXISTS (SELECT CODCFO FROM ZMDFCFOCRM WHERE CODCFO = (SELECT 'C'+CAST(RIGHT(MAX(CODCFO),7)+1 AS varchar(7)) FROM FCFO WHERE CODCFO LIKE 'C%'))
 
-- open cursor and fetch first row into variables
OPEN zmd_cursor
FETCH NEXT FROM zmd_cursor into @CODCOLIGADA, @CODCFO, @IDCFO, @NOME, @NOMEFANTASIA, @PESSOAFISOUJUR, @PAGREC, @CEP, @RUA, @NUMERO, @COMPLEMENTO, @BAIRRO, @CODETD, @TELEFONE, @CGCCFO, @CODMUNICIPIO, @ULTIMO_CFO, @ULTIMO_IDCFO, @USUARIO, @DTIMPORT
 
-- check for a new row
WHILE @@FETCH_STATUS=0
BEGIN
-- do complex operation here
--Insert into #tmp
INSERT INTO ZMDFCFOCRM(CODCOLIGADA, CODCFO, IDCFO, NOMEFANTASIA, NOME, PESSOAFISOUJUR, PAGREC, CEP, RUA, NUMERO, COMPLEMENTO, BAIRRO, CODETD, TELEFONE, CGCCFO, CODMUNICIPIO, RECCREATEDON, RECCREATEDBY, RECMODIFIEDON, RECMODIFIEDBY)
	SELECT DISTINCT  @CODCOLIGADA, @CODCFO, @IDCFO, @NOME, @NOMEFANTASIA, @PESSOAFISOUJUR, @PAGREC, @CEP, @RUA, @NUMERO, @COMPLEMENTO, @BAIRRO, @CODETD, @TELEFONE, @CGCCFO, @CODMUNICIPIO, @DTIMPORT, @USUARIO, @DTIMPORT, @USUARIO

	--UPDATE GAUTOINC SET VALAUTOINC = @IDCFO WHERE NOMETABELA = 'FCFO' AND CODSISTEMA = 'F' AND NOMECOLUNA = 'IDCFO' AND CODCOLIGADA = 0

-- get next available row into variables
FETCH NEXT FROM zmd_cursor into @CODCOLIGADA, @CODCFO, @IDCFO, @NOME, @NOMEFANTASIA, @PESSOAFISOUJUR, @PAGREC, @CEP, @RUA, @NUMERO, @COMPLEMENTO, @BAIRRO, @CODETD, @TELEFONE, @CGCCFO, @CODMUNICIPIO, @ULTIMO_CFO, @ULTIMO_IDCFO, @USUARIO, @DTIMPORT
END
close zmd_cursor
Deallocate zmd_cursor


/**********************************************************/


DECLARE clifor_cursor CURSOR FOR 
SELECT DISTINCT CODCOLIGADA AS CODCOLIGADA
		   , CODCFO AS CODCFO
		   , IDCFO AS IDCFO
		   --, (SELECT MAX(IDCFO) FROM FCFO WITH (NOLOCK))+1 AS IDCFO
		   , NOME AS NOME
		   , NOMEFANTASIA AS NOMEFANTASIA
		   , PESSOAFISOUJUR AS PESSOAFISOUJUR
		   , PAGREC AS PAGREC
		   , CEP AS CEP
		   , RUA AS RUA
		   , NUMERO AS NUMERO
		   , COMPLEMENTO AS COMPLEMENTO
		   , BAIRRO AS BAIRRO
		   --, IDPAIS AS IDPAIS
		   , CODETD AS CODETD
		   , TELEFONE AS TELEFONE
		   , CGCCFO AS CGCCFO
		   , CODMUNICIPIO AS CODMUNICIPIO
		   , 1 AS ATIVO
		   , 0 AS RAMOATIV 
		   , 0 AS TIPOCONTRIBUINTE 
		   , 0 AS NACIONALIDADE 
		   , 0 AS CALCULAAVP 
		   , 0 AS ENTIDADEEXECUTORAPAA 
		   , 0 AS APOSENTADOOUPENSIONISTA 
		   , 'crm' AS USUARIO
		   , GETDATE() AS DTIMPORT


    FROM
        ZMDFCFOCRM WITH (NOLOCK)

	WHERE NOT EXISTS (SELECT CODCFO FROM FCFO WHERE REPLACE(REPLACE(CGCCFO,'.',''),'-','') = ZMDFCFOCRM.CGCCFO)
    --WHERE NOT EXISTS (SELECT CODCFO FROM ZMDFCFOCRM WHERE CODCFO = (SELECT 'C'+CAST(RIGHT(MAX(CODCFO),7)+1 AS varchar(7)) FROM FCFO WHERE CODCFO LIKE 'C%'))
 
-- open cursor and fetch first row into variables
OPEN clifor_cursor
FETCH NEXT FROM clifor_cursor into @CODCOLIGADA, @CODCFO, @IDCFO, @NOME, @NOMEFANTASIA, @PESSOAFISOUJUR, @PAGREC, @CEP, @RUA, @NUMERO, @COMPLEMENTO, @BAIRRO, @CODETD, @TELEFONE, @CGCCFO, @CODMUNICIPIO, @ATIVO,  @RAMOATIV, @TIPOCONTRIBUINTE, @NACIONALIDADE, @CALCULAAVP, @ENTIDADEEXECUTORAPAA, @APOSENTADOOUPENSIONISTA, @USUARIO, @DTIMPORT
 
-- check for a new row
WHILE @@FETCH_STATUS=0
BEGIN
-- do complex operation here
--Insert into #tmp
INSERT INTO FCFO(CODCOLIGADA, CODCFO, IDCFO, NOMEFANTASIA, NOME, PESSOAFISOUJUR, PAGREC, CEP, RUA, NUMERO, COMPLEMENTO, BAIRRO, CODETD, TELEFONE, CGCCFO, CODMUNICIPIO, ATIVO,  RAMOATIV, TIPOCONTRIBUINTEINSS, NACIONALIDADE, CALCULAAVP, ENTIDADEEXECUTORAPAA, APOSENTADOOUPENSIONISTA, RECCREATEDON, RECCREATEDBY, RECMODIFIEDON, RECMODIFIEDBY)
	SELECT DISTINCT  @CODCOLIGADA, @CODCFO, @IDCFO, @NOME, @NOMEFANTASIA, @PESSOAFISOUJUR, @PAGREC, @CEP, @RUA, @NUMERO, @COMPLEMENTO, @BAIRRO, @CODETD, @TELEFONE, @CGCCFO, @CODMUNICIPIO, @ATIVO,  @RAMOATIV, @TIPOCONTRIBUINTE, @NACIONALIDADE, @CALCULAAVP, @ENTIDADEEXECUTORAPAA, @APOSENTADOOUPENSIONISTA, @DTIMPORT, @USUARIO, @DTIMPORT, @USUARIO

	UPDATE GAUTOINC SET VALAUTOINC = @IDCFO WHERE NOMETABELA = 'FCFO' AND CODSISTEMA = 'F' AND NOMECOLUNA = 'IDCFO' AND CODCOLIGADA = 0

-- get next available row into variables
FETCH NEXT FROM clifor_cursor into @CODCOLIGADA, @CODCFO, @IDCFO, @NOME, @NOMEFANTASIA, @PESSOAFISOUJUR, @PAGREC, @CEP, @RUA, @NUMERO, @COMPLEMENTO, @BAIRRO, @CODETD, @TELEFONE, @CGCCFO, @CODMUNICIPIO, @ATIVO,  @RAMOATIV, @TIPOCONTRIBUINTE, @NACIONALIDADE, @CALCULAAVP, @ENTIDADEEXECUTORAPAA, @APOSENTADOOUPENSIONISTA, @USUARIO, @DTIMPORT
END
close clifor_cursor
Deallocate clifor_cursor






/*****************************************/

DECLARE scandidato_cursor CURSOR FOR 
SELECT DISTINCT #Temp_CandidatoCRM.CODCOLIGADA
				, IDPROCSEL AS IDPROCSEL
				, NUMEROINSCPROCSEL AS NUMEROINSCPROCSEL
				, #Temp_CandidatoCRM.NOME AS NOME
				, SEXO AS SEXO
				, DATANASC AS DATANASC
				--, CIDADE AS CIDADENASC
				--, ESTADO AS UFNASC
				, PAI AS PAI
				, MAE AS MAE
				, CPFFIADOR AS CPFFIADOR
				, IDENT AS IDENT
				, CPFALUNO AS CPFALUNO
				, LOGRADOURO AS LOGRADOURO
				, COMPLEMENTO AS COMPLEMENTO
				, NUMEROIMOVEL AS NUMEROIMOVEL
				, BAIRRO AS BAIRRO
				, CIDADE AS CIDADE
				, ESTADO AS ESTADO
				, CEP AS CEP
				, TELEFONE AS TELEFONE
				, USUARIO AS USUARIO
				, DTIMPORT AS DTIMPORT
				, IDOPORTUNIDADE_CRM AS IDOPORTUNIDADE_CRM
				, CURSO AS CURSO
				, PONTUACAO AS PONTUACAO
				, CODCURSO AS CODCURSO
				, #Temp_CandidatoCRM.CODTIPOCURSO AS CODTIPOCURSO
				, #Temp_CandidatoCRM.IDHABILITACAOFILIAL AS IDHABILITACAOFILIAL
				, PERIODO AS PERIODO
				, OPCAO AS OPCAO
	


    FROM
        #Temp_CandidatoCRM 

	WHERE NOT EXISTS (SELECT NUMEROINSCPROCSEL FROM SCANDIDATOPROCSEL WITH (NOLOCK) WHERE /*NUMEROINSCPROCSEL = #Temp_CandidatoCRM.NUMEROINSCPROCSEL AND*/ CPFALUNO = #Temp_CandidatoCRM.CPFALUNO)
	AND NOT EXISTS (SELECT RA FROM SALUNO WITH (NOLOCK) JOIN PPESSOA WITH (NOLOCK) ON PPESSOA.CODIGO = SALUNO.CODPESSOA 
						WHERE PPESSOA.CPF = #Temp_CandidatoCRM.CPFALUNO) 
    --WHERE NOT EXISTS (SELECT CODCFO FROM ZMDFCFOCRM WHERE CODCFO = (SELECT 'C'+CAST(RIGHT(MAX(CODCFO),7)+1 AS varchar(7)) FROM FCFO WHERE CODCFO LIKE 'C%'))
 
-- open cursor and fetch first row into variables
OPEN scandidato_cursor
FETCH NEXT FROM scandidato_cursor into @CODCOLIGADA, @IDPROCSEL, @NUMEROINSCPROCSEL, @NOME_ALUNO, @SEXO_ALUNO, @DATANASC, @PAI, @MAE, @CPFFIADOR, @IDENT, @CPFALUNO, @LOGRADOURO_ALUNO, @COMPLEMENTO, @NUMEROIMOVEL, @BAIRRO, @CIDADE_ALUNO, @ESTADO_ALUNO, @CEP_ALUNO, @TELEFONE_ALUNO, @USUARIO, @DTIMPORT, @IDOPORTUNIDADE_CRM, @CURSO, @PONTUACAO, @CODCURSO, @CODTIPOCURSO, @IDHABILITACAOFILIAL, @PERIODO, @OPCAO
 
-- check for a new row
WHILE @@FETCH_STATUS=0
BEGIN
-- do complex operation here
--Insert into #tmp
INSERT INTO SCANDIDATOPROCSEL(CODCOLIGADA, IDPROCSEL, NUMEROINSCPROCSEL, NOME, SEXO, DATANASC, PAI, MAE, CPFFIADOR, IDENT, CPFALUNO, LOGRADOURO, COMPLEMENTO, NUMEROIMOVEL, BAIRRO, CIDADE, ESTADO, CEP, TELEFONE, IDOPORTUNIDADE_CRM, PERIODO, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
	SELECT DISTINCT  @CODCOLIGADA, @IDPROCSEL, @NUMEROINSCPROCSEL, @NOME_ALUNO, @SEXO_ALUNO, @DATANASC, @PAI, @MAE, @CPFFIADOR, @IDENT, @CPFALUNO, @LOGRADOURO_ALUNO, @COMPLEMENTO_ALUNO, @NUMEROIMOVEL, @BAIRRO_ALUNO, @CIDADE_ALUNO, @ESTADO_ALUNO, @CEP_ALUNO, @TELEFONE_ALUNO, @IDOPORTUNIDADE_CRM, @PERIODO, @USUARIO, @DTIMPORT, @USUARIO, @DTIMPORT

--UPDATE [172.16.254.42].salesforce.dbo.students SET INTEGRADO = 1 WHERE NUMEROINSCPROCSEL = @IDOPORTUNIDADE_CRM


-- get next available row into variables
FETCH NEXT FROM scandidato_cursor into @CODCOLIGADA, @IDPROCSEL, @NUMEROINSCPROCSEL, @NOME_ALUNO, @SEXO_ALUNO, @DATANASC, @PAI, @MAE, @CPFFIADOR, @IDENT, @CPFALUNO, @LOGRADOURO_ALUNO, @COMPLEMENTO, @NUMEROIMOVEL, @BAIRRO, @CIDADE_ALUNO, @ESTADO_ALUNO, @CEP_ALUNO, @TELEFONE_ALUNO, @USUARIO, @DTIMPORT, @IDOPORTUNIDADE_CRM, @CURSO, @PONTUACAO, @CODCURSO, @CODTIPOCURSO, @IDHABILITACAOFILIAL, @PERIODO, @OPCAO
END
close scandidato_cursor
Deallocate scandidato_cursor


/*****************************************/

DECLARE sopcao_cursor CURSOR FOR 
SELECT DISTINCT CODCOLIGADA AS CODCOLIGADA
				, IDPERLET AS IDPERLET
				, IDPROCSEL AS IDPROCSEL
				, NUMEROINSCPROCSEL AS NUMEROINSCPROCSEL
				, CODCURSO AS CODCURSO
				, OPCAO AS OPCAO
				, PONTUACAO AS PONTUACAO
				, IDHABILITACAOFILIAL AS IDHABILITACAOFILIAL
				, RECCREATEDBY AS RECCREATEDBY
				, RECCREATEDON AS RECCREATEDON


FROM #Temp_CursoCandidatoCRM
	

	WHERE NOT EXISTS (SELECT NUMEROINSCPROCSEL FROM SOPCAOCANDIDATO WHERE NUMEROINSCPROCSEL = #Temp_CursoCandidatoCRM.NUMEROINSCPROCSEL)
    --WHERE NOT EXISTS (SELECT CODCFO FROM ZMDFCFOCRM WHERE CODCFO = (SELECT 'C'+CAST(RIGHT(MAX(CODCFO),7)+1 AS varchar(7)) FROM FCFO WHERE CODCFO LIKE 'C%'))
 
-- open cursor and fetch first row into variables
OPEN sopcao_cursor
FETCH NEXT FROM sopcao_cursor into @CODCOLIGADA, @IDPERLET, @IDPROCSEL, @NUMEROINSCPROCSEL, @CODCURSO, @OPCAO, @PONTUACAO, @IDHABILITACAOFILIAL, @USUARIO, @DTIMPORT
 
-- check for a new row
WHILE @@FETCH_STATUS=0
BEGIN
-- do complex operation here
--Insert into #tmp
INSERT INTO SOPCAOCANDIDATO(CODCOLIGADA, IDPERLET, IDPROCSEL, NUMEROINSCPROCSEL, CODCURSO, OPCAO, PONTUACAO, IDHABILITACAOFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
	SELECT DISTINCT  @CODCOLIGADA, @IDPERLET, @IDPROCSEL, @NUMEROINSCPROCSEL, @CODCURSO, @OPCAO, @PONTUACAO, @IDHABILITACAOFILIAL, @USUARIO, @DTIMPORT, @USUARIO, @DTIMPORT

	

-- get next available row into variables
FETCH NEXT FROM sopcao_cursor into @CODCOLIGADA, @IDPERLET, @IDPROCSEL, @NUMEROINSCPROCSEL, @CODCURSO, @OPCAO, @PONTUACAO, @IDHABILITACAOFILIAL, @USUARIO, @DTIMPORT
END
close sopcao_cursor
Deallocate sopcao_cursor





/*********************************************/

DECLARE adiantamento_cursor CURSOR FOR 



SELECT  CODCOLIGADA
				, IDLAN
				, NUMERODOCUMENTO
				, NFOUDUP
				, CLASSIFICACAO
				, PAGREC
				, STATUSLAN
				, DATAVENCIMENTO
				, DATAEMISSAO
				, VALORORIGINAL
				, VALORBAIXADO
				, VALORCAP
				, VALORJUROS
				, VALORDESCONTO
				, VALOROP1
				, VALOROP2
				, VALOROP3
				, VALOROP4
				, VALOROP5
				, VALOROP6
				, VALOROP7
				, VALOROP8
				, VALORMULTA
				, VALORADIANTAMENTO
				, VALORDEVOLUCAO
				, JUROSDIA
				, CODCOLCFO
				, CODCFO
				, CODCOLCXA
				, CODCXA
				, CODTDO
				, CODFILIAL
				, TIPOCONTABILLAN
				, STATUSEXPORTACAO
				, NUMLOTECONTABIL
				, STATUSEXTRATO
				, CNABSTATUS
				, REEMBOLSAVEL
				, BAIXAAUTORIZADA
				, TEMCHEQUEPARCIAL
				, JAIMPRIMIU
				, NUMBLOQUEIOS
				, TIPOJUROSDIA
				, ALTERACAOBLOQUEADA
				, MULTADIA
				, DESCONTADO
				, VALORINSS
				, VALORDEDUCAO
				, INSSEMOUTRAEMPRESA
				, PERCENTBASEINSS
				, PERCBASEINSSEMPREGADO
				, IMPOSTOEDITADO
				, REUTILIZACAO
				, VALORSESTSENAT
				, VRPERDAFINANCEIRA
				, STATUSDDA
				, STATUSAVP
				, VALORORIGINALBX
				, VALORDESCONTOBX
				, VALORMULTABX
				, VALORCAPBX
				, VALOROP1BX
				, VALOROP2BX
				, VALOROP3BX
				, VALOROP4BX
				, VALOROP5BX
				, VALOROP6BX
				, VALOROP7BX
				, VALOROP8BX
				, VALORINSSBX
				, VALORIRRFBX
				, VALORSESTSENATBX
				, VALORDEVOLUCAOBX
				, VALORNOTACREDITOBX
				, VALORADIANTAMENTOBX
				, VALORJUROSVENDORBX
				, VALORRETENCOESBX
				, VALORPERDAFINANCEIRABX
				, VALORVINCULADO
				, MODELOCONTABILIZACAO
				, MODELOCONTABILIZACAOBAIXA
				, VALORDESCONTODUPLICATA
				, VALORDESCONTOACORDO
				, VALORACRESCIMOACORDO
				, STATUSORCAMENTO
				, VALORDESCONTOPONTUALBX
				, IDXCX
				, IDTRANSACAO
				, DATABAIXA
				, VALORBAIXA
				--, VALORINSS
				, VALORIRRF
				--, VALORSESTSENAT
				--, VALORDEVOLUCAO
				, VALORNOTACREDITO
				, VALORNOTACREDITOADIANTAMENTO
				, VALORJUROSVENDOR
				, VALORRETENCOES
				, VALORPERDAFINANCEIRA
				, VALORJUROSACORDO
				--, VALORDESCONTOACORDO
				--, VALORACRESCIMOACORDO
				, TIPOBAIXA
				, STATUS
				, DIFBAIXAPARCIAL
				, TIPORETORNOBANCARIO
				, ORIGEMVALORDESCONTO
				, ORIGEMVALORJUROS
				, ORIGEMVALORMULTA
				, ORIGEMVALORCAP
				, ORIGEMVALOROP1
				, ORIGEMVALOROP2
				, ORIGEMVALOROP3
				, ORIGEMVALOROP4
				, ORIGEMVALOROP5
				, ORIGEMVALOROP6
				, ORIGEMVALOROP7
				, ORIGEMVALOROP8
				, VALORDESCONTOPONTUAL
				, IDBAIXA
				, TIPO
				, COMPENSADO
				, RECONCILIADO
				--, STATUSEXPORTACAO
				, VALOR
				, DATA
				, CONTABIL
				, ECHEQUE
				, TIPOCUSTODIA
				, LIBERACAOAUTORIZADA
				, CODMOEDA
				, SERIEDOCUMENTO
				, CODAPLICACAO
				, HISTORICO
				, USUARIO
				, DTIMPORT



FROM #Temp_Adiantamento WHERE NOT EXISTS (SELECT IDLAN FROM FLAN WITH (NOLOCK) WHERE IDLAN = #Temp_Adiantamento.IDLAN AND CODCOLIGADA = #Temp_Adiantamento.CODCOLIGADA)
	

	--WHERE NOT EXISTS (SELECT IDLAN FROM FLAN WITH (NOLOCK) WHERE IDLAN = (SELECT MAX(VALAUTOINC)+1 FROM GAUTOINC WITH (NOLOCK) WHERE NOMETABELA = 'FLAN' AND NOMECOLUNA = 'IDLAN' AND CODCOLIGADA = 1 AND CODSISTEMA = 'F' AND CODAUTOINC = 'IDLAN') AND CODCOLIGADA = #Temp_CliforCRM.CODCOLIGADA)
    --WHERE NOT EXISTS (SELECT CODCFO FROM ZMDFCFOCRM WHERE CODCFO = (SELECT 'C'+CAST(RIGHT(MAX(CODCFO),7)+1 AS varchar(7)) FROM FCFO WHERE CODCFO LIKE 'C%'))
 
-- open cursor and fetch first row into variables
OPEN adiantamento_cursor
FETCH NEXT FROM adiantamento_cursor into @CODCOLIGADA
				, @IDLAN
				, @NUMERODOCUMENTO
				, @NFOUDUP
				, @CLASSIFICACAO
				, @PAGREC
				, @STATUSLAN
				, @DATAVENCIMENTO
				, @DATAEMISSAO
				, @VALORORIGINAL
				, @VALORBAIXADO
				, @VALORCAP
				, @VALORJUROS
				, @VALORDESCONTO
				, @VALOROP1
				, @VALOROP2
				, @VALOROP3
				, @VALOROP4
				, @VALOROP5
				, @VALOROP6
				, @VALOROP7
				, @VALOROP8
				, @VALORMULTA
				, @VALORADIANTAMENTO
				, @VALORDEVOLUCAO
				, @JUROSDIA
				, @CODCOLCFO
				, @CODCFO
				, @CODCOLCXA
				, @CODCXA
				, @CODTDO
				, @CODFILIAL
				, @TIPOCONTABILLAN
				, @STATUSEXPORTACAO
				, @NUMLOTECONTABIL
				, @STATUSEXTRATO
				, @CNABSTATUS
				, @REEMBOLSAVEL
				, @BAIXAAUTORIZADA
				, @TEMCHEQUEPARCIAL
				, @JAIMPRIMIU
				, @NUMBLOQUEIOS
				, @TIPOJUROSDIA
				, @ALTERACAOBLOQUEADA
				, @MULTADIA
				, @DESCONTADO
				, @VALORINSS
				, @VALORDEDUCAO
				, @INSSEMOUTRAEMPRESA
				, @PERCENTBASEINSS
				, @PERCBASEINSSEMPREGADO
				, @IMPOSTOEDITADO
				, @REUTILIZACAO
				, @VALORSESTSENAT
				, @VRPERDAFINANCEIRA
				, @STATUSDDA
				, @STATUSAVP
				, @VALORORIGINALBX
				, @VALORDESCONTOBX
				, @VALORMULTABX
				, @VALORCAPBX
				, @VALOROP1BX
				, @VALOROP2BX
				, @VALOROP3BX
				, @VALOROP4BX
				, @VALOROP5BX
				, @VALOROP6BX
				, @VALOROP7BX
				, @VALOROP8BX
				, @VALORINSSBX
				, @VALORIRRFBX
				, @VALORSESTSENATBX
				, @VALORDEVOLUCAOBX
				, @VALORNOTACREDITOBX
				, @VALORADIANTAMENTOBX
				, @VALORJUROSVENDORBX
				, @VALORRETENCOESBX
				, @VALORPERDAFINANCEIRABX
				, @VALORVINCULADO
				, @MODELOCONTABILIZACAO
				, @MODELOCONTABILIZACAOBAIXA
				, @VALORDESCONTODUPLICATA
				, @VALORDESCONTOACORDO
				, @VALORACRESCIMOACORDO
				, @STATUSORCAMENTO
				, @VALORDESCONTOPONTUALBX
				, @IDXCX
				, @IDTRANSACAO
				, @DATABAIXA
				, @VALORBAIXA
				--, @VALORINSS
				, @VALORIRRF
				--, @VALORSESTSENAT
				--, @VALORDEVOLUCAO
				, @VALORNOTACREDITO
				, @VALORNOTACREDITOADIANTAMENTO
				, @VALORJUROSVENDOR
				, @VALORRETENCOES
				, @VALORPERDAFINANCEIRA
				, @VALORJUROSACORDO
				--, @VALORDESCONTOACORDO
				--, @VALORACRESCIMOACORDO
				, @TIPOBAIXA
				, @STATUS
				, @DIFBAIXAPARCIAL
				, @TIPORETORNOBANCARIO
				, @ORIGEMVALORDESCONTO
				, @ORIGEMVALORJUROS
				, @ORIGEMVALORMULTA
				, @ORIGEMVALORCAP
				, @ORIGEMVALOROP1
				, @ORIGEMVALOROP2
				, @ORIGEMVALOROP3
				, @ORIGEMVALOROP4
				, @ORIGEMVALOROP5
				, @ORIGEMVALOROP6
				, @ORIGEMVALOROP7
				, @ORIGEMVALOROP8
				, @VALORDESCONTOPONTUAL
				, @IDBAIXA
				, @TIPO
				, @COMPENSADO
				, @RECONCILIADO
				--, @STATUSEXPORTACAO
				, @VALOR
				, @DATA
				, @CONTABIL
				, @ECHEQUE
				, @TIPOCUSTODIA
				, @LIBERACAOAUTORIZADA
				, @CODMOEDA
				, @SERIEDOCUMENTO
				, @CODAPLICACAO
				, @HISTORICO
				, @USUARIO
				, @DTIMPORT
 
-- check for a new row
WHILE @@FETCH_STATUS=0
BEGIN
-- do complex operation here
--Insert into #tmp
INSERT INTO FLAN(CODCOLIGADA
, IDLAN
, NUMERODOCUMENTO
, NFOUDUP
, CLASSIFICACAO
, PAGREC
, STATUSLAN
, DATAVENCIMENTO
, DATAEMISSAO
, VALORORIGINAL
, VALORBAIXADO
, VALORCAP
, VALORJUROS
, VALORDESCONTO
, VALOROP1
, VALOROP2
, VALOROP3
, VALOROP4
, VALOROP5
, VALOROP6
, VALOROP7
, VALOROP8
, VALORMULTA
, VALORADIANTAMENTO
, VALORDEVOLUCAO
, JUROSDIA
, CODCOLCFO
, CODCFO
, CODCOLCXA
, CODCXA
, CODTDO
, CODFILIAL
, TIPOCONTABILLAN
, STATUSEXPORTACAO
, NUMLOTECONTABIL
, STATUSEXTRATO
, CNABSTATUS
, REEMBOLSAVEL
, BAIXAAUTORIZADA
, TEMCHEQUEPARCIAL
, JAIMPRIMIU
, NUMBLOQUEIOS
, TIPOJUROSDIA
, ALTERACAOBLOQUEADA
, MULTADIA
, DESCONTADO
, VALORINSS
, VALORDEDUCAO
, INSSEMOUTRAEMPRESA
, PERCENTBASEINSS
, PERCBASEINSSEMPREGADO
, IMPOSTOEDITADO
, REUTILIZACAO
, VALORSESTSENAT
, VRPERDAFINANCEIRA
, STATUSDDA
, STATUSAVP
, VALORORIGINALBX
, VALORDESCONTOBX
, VALORMULTABX
, VALORCAPBX
, VALOROP1BX
, VALOROP2BX
, VALOROP3BX
, VALOROP4BX
, VALOROP5BX
, VALOROP6BX
, VALOROP7BX
, VALOROP8BX
, VALORINSSBX
, VALORIRRFBX
, VALORSESTSENATBX
, VALORDEVOLUCAOBX
, VALORNOTACREDITOBX
, VALORADIANTAMENTOBX
, VALORJUROSVENDORBX
, VALORRETENCOESBX
, VALORPERDAFINANCEIRABX
, VALORVINCULADO
, MODELOCONTABILIZACAO
, MODELOCONTABILIZACAOBAIXA
, VALORDESCONTODUPLICATA
, VALORDESCONTOACORDO
, VALORACRESCIMOACORDO
, STATUSORCAMENTO
, VALORDESCONTOPONTUALBX
, HISTORICO
, CODMOEVALORORIGINAL
, CODAPLICACAO
, RECCREATEDBY
, RECCREATEDON
, RECMODIFIEDBY
, RECMODIFIEDON)

SELECT DISTINCT  @CODCOLIGADA
, @IDLAN
, @NUMERODOCUMENTO
, @NFOUDUP
, @CLASSIFICACAO
, @PAGREC
, @STATUSLAN
, @DATAVENCIMENTO
, @DATAEMISSAO
, @VALORORIGINAL
, @VALORBAIXADO
, @VALORCAP
, @VALORJUROS
, @VALORDESCONTO
, @VALOROP1
, @VALOROP2
, @VALOROP3
, @VALOROP4
, @VALOROP5
, @VALOROP6
, @VALOROP7
, @VALOROP8
, @VALORMULTA
, @VALORADIANTAMENTO
, @VALORDEVOLUCAO
, @JUROSDIA
, @CODCOLCFO
, @CODCFO
, @CODCOLCXA
, @CODCXA
, @CODTDO
, @CODFILIAL
, @TIPOCONTABILLAN
, @STATUSEXPORTACAO
, @NUMLOTECONTABIL
, @STATUSEXTRATO
, @CNABSTATUS
, @REEMBOLSAVEL
, @BAIXAAUTORIZADA
, @TEMCHEQUEPARCIAL
, @JAIMPRIMIU
, @NUMBLOQUEIOS
, @TIPOJUROSDIA
, @ALTERACAOBLOQUEADA
, @MULTADIA
, @DESCONTADO
, @VALORINSS
, @VALORDEDUCAO
, @INSSEMOUTRAEMPRESA
, @PERCENTBASEINSS
, @PERCBASEINSSEMPREGADO
, @IMPOSTOEDITADO
, @REUTILIZACAO
, @VALORSESTSENAT
, @VRPERDAFINANCEIRA
, @STATUSDDA
, @STATUSAVP
, @VALORORIGINALBX
, @VALORDESCONTOBX
, @VALORMULTABX
, @VALORCAPBX
, @VALOROP1BX
, @VALOROP2BX
, @VALOROP3BX
, @VALOROP4BX
, @VALOROP5BX
, @VALOROP6BX
, @VALOROP7BX
, @VALOROP8BX
, @VALORINSSBX
, @VALORIRRFBX
, @VALORSESTSENATBX
, @VALORDEVOLUCAOBX
, @VALORNOTACREDITOBX
, @VALORADIANTAMENTOBX
, @VALORJUROSVENDORBX
, @VALORRETENCOESBX
, @VALORPERDAFINANCEIRABX
, @VALORVINCULADO
, @MODELOCONTABILIZACAO
, @MODELOCONTABILIZACAOBAIXA
, @VALORDESCONTODUPLICATA
, @VALORDESCONTOACORDO
, @VALORACRESCIMOACORDO
, @STATUSORCAMENTO
, @VALORDESCONTOPONTUALBX
, @HISTORICO
, @CODMOEDA
, @CODAPLICACAO
, @USUARIO
, @DTIMPORT
, @USUARIO
, @DTIMPORT;

INSERT INTO FXCX(CODCOLIGADA
, IDXCX
, NUMERODOCUMENTO
, TIPO
, COMPENSADO
, RECONCILIADO
, STATUSEXPORTACAO
, CODCXA
, CODCOLCXA
, CODFILIAL
, VALOR
, DATA
, CONTABIL
, ECHEQUE
, TIPOCUSTODIA
, LIBERACAOAUTORIZADA
, MODELOCONTABILIZACAO
, HISTORICO
, RECCREATEDBY
, RECCREATEDON
, RECMODIFIEDBY
, RECMODIFIEDON)

SELECT @CODCOLIGADA
, @IDXCX
, @NUMERODOCUMENTO
, @TIPO
, @COMPENSADO
, @RECONCILIADO
, @STATUSEXPORTACAO
, @CODCXA
, @CODCOLCXA
, @CODFILIAL
, @VALOR
, @DATA
, @CONTABIL
, @ECHEQUE
, @TIPOCUSTODIA
, @LIBERACAOAUTORIZADA
, @MODELOCONTABILIZACAO
, @HISTORICO
, @USUARIO
, @DTIMPORT
, @USUARIO
, @DTIMPORT;


INSERT INTO FLANBAIXA(CODCOLIGADA, IDLAN, IDBAIXA, IDXCX, CODCOLCXA, CODCXA, IDTRANSACAO, DATABAIXA, VALORBAIXA, VALORORIGINAL, VALORDESCONTO, VALORJUROS, VALORMULTA, VALORCAP,
VALOROP1, VALOROP2, VALOROP3, VALOROP4, VALOROP5, VALOROP6, VALOROP7, VALOROP8, VALORINSS, VALORIRRF, VALORSESTSENAT, VALORDEVOLUCAO, VALORNOTACREDITO, VALORNOTACREDITOADIANTAMENTO,
VALORVINCULADO, VALORJUROSVENDOR, VALORRETENCOES, VALORPERDAFINANCEIRA,VALORJUROSACORDO, VALORDESCONTOACORDO, VALORACRESCIMOACORDO, TIPOBAIXA, STATUS, MODELOCONTABILIZACAO, DIFBAIXAPARCIAL, 
TIPORETORNOBANCARIO, ORIGEMVALORDESCONTO, ORIGEMVALORJUROS, ORIGEMVALORMULTA, ORIGEMVALORCAP, ORIGEMVALOROP1, ORIGEMVALOROP2, ORIGEMVALOROP3, ORIGEMVALOROP4,
ORIGEMVALOROP5, ORIGEMVALOROP6, ORIGEMVALOROP7, ORIGEMVALOROP8, STATUSEXPORTACAO, VALORDESCONTOPONTUAL, CODCOLXCX, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)

SELECT @CODCOLIGADA
, @IDLAN
, @IDBAIXA
, @IDXCX
, @CODCOLCXA
, @CODCXA
, @IDTRANSACAO
, @DATABAIXA
, @VALORBAIXA
, @VALORORIGINAL
, @VALORDESCONTO
, @VALORJUROS
, @VALORMULTA
, @VALORCAP
, @VALOROP1
, @VALOROP2
, @VALOROP3
, @VALOROP4
, @VALOROP5
, @VALOROP6
, @VALOROP7
, @VALOROP8
, @VALORINSS
, @VALORIRRF
, @VALORSESTSENAT
, @VALORDEVOLUCAO
, @VALORNOTACREDITO
, @VALORNOTACREDITOADIANTAMENTO
, @VALORVINCULADO
, @VALORJUROSVENDOR
, @VALORRETENCOES
, @VALORPERDAFINANCEIRA
, @VALORJUROSACORDO
, @VALORDESCONTOACORDO
, @VALORACRESCIMOACORDO
, @TIPOBAIXA
, @STATUS
, @MODELOCONTABILIZACAO
, @DIFBAIXAPARCIAL
, @TIPORETORNOBANCARIO
, @ORIGEMVALORDESCONTO
, @ORIGEMVALORJUROS
, @ORIGEMVALORMULTA
, @ORIGEMVALORCAP
, @ORIGEMVALOROP1
, @ORIGEMVALOROP2
, @ORIGEMVALOROP3
, @ORIGEMVALOROP4
, @ORIGEMVALOROP5
, @ORIGEMVALOROP6
, @ORIGEMVALOROP7
, @ORIGEMVALOROP8
, @STATUSEXPORTACAO
, @VALORDESCONTOPONTUAL
, @CODCOLIGADA
, @USUARIO
, @DTIMPORT
, @USUARIO
, @DTIMPORT;


UPDATE  GAUTOINC SET VALAUTOINC = @IDLAN WHERE NOMETABELA = 'FLAN' AND NOMECOLUNA = 'IDLAN' AND CODCOLIGADA = 1 AND CODSISTEMA = 'F' AND CODAUTOINC = 'IDLAN';
--UPDATE  GAUTOINC SET VALAUTOINC = @NUMERODOCUMENTO 
UPDATE GAUTOINC SET VALAUTOINC = @IDBAIXA WHERE CODCOLIGADA = 1 AND NOMETABELA = 'FLANBAIXA' AND CODAUTOINC = 'IDBAIXA' AND NOMECOLUNA = 'IDBAIXA' AND CODSISTEMA = 'F';
UPDATE GAUTOINC SET VALAUTOINC = @IDTRANSACAO WHERE CODCOLIGADA = 1 AND NOMETABELA = 'FLANBAIXA' AND CODAUTOINC = 'IDTRANSACAO' AND NOMECOLUNA = 'IDTRANSACAO' AND CODSISTEMA = 'F';
UPDATE GAUTOINC SET VALAUTOINC = @IDXCX WHERE CODCOLIGADA = 1 AND CODSISTEMA = 'F' AND NOMECOLUNA = 'IDXCX' AND CODAUTOINC = 'IDXCX' AND NOMETABELA = 'FXCX';

	

-- get next available row into variables
FETCH NEXT FROM adiantamento_cursor into 
@CODCOLIGADA
				, @IDLAN
				, @NUMERODOCUMENTO
				, @NFOUDUP
				, @CLASSIFICACAO
				, @PAGREC
				, @STATUSLAN
				, @DATAVENCIMENTO
				, @DATAEMISSAO
				, @VALORORIGINAL
				, @VALORBAIXADO
				, @VALORCAP
				, @VALORJUROS
				, @VALORDESCONTO
				, @VALOROP1
				, @VALOROP2
				, @VALOROP3
				, @VALOROP4
				, @VALOROP5
				, @VALOROP6
				, @VALOROP7
				, @VALOROP8
				, @VALORMULTA
				, @VALORADIANTAMENTO
				, @VALORDEVOLUCAO
				, @JUROSDIA
				, @CODCOLCFO
				, @CODCFO
				, @CODCOLCXA
				, @CODCXA
				, @CODTDO
				, @CODFILIAL
				, @TIPOCONTABILLAN
				, @STATUSEXPORTACAO
				, @NUMLOTECONTABIL
				, @STATUSEXTRATO
				, @CNABSTATUS
				, @REEMBOLSAVEL
				, @BAIXAAUTORIZADA
				, @TEMCHEQUEPARCIAL
				, @JAIMPRIMIU
				, @NUMBLOQUEIOS
				, @TIPOJUROSDIA
				, @ALTERACAOBLOQUEADA
				, @MULTADIA
				, @DESCONTADO
				, @VALORINSS
				, @VALORDEDUCAO
				, @INSSEMOUTRAEMPRESA
				, @PERCENTBASEINSS
				, @PERCBASEINSSEMPREGADO
				, @IMPOSTOEDITADO
				, @REUTILIZACAO
				, @VALORSESTSENAT
				, @VRPERDAFINANCEIRA
				, @STATUSDDA
				, @STATUSAVP
				, @VALORORIGINALBX
				, @VALORDESCONTOBX
				, @VALORMULTABX
				, @VALORCAPBX
				, @VALOROP1BX
				, @VALOROP2BX
				, @VALOROP3BX
				, @VALOROP4BX
				, @VALOROP5BX
				, @VALOROP6BX
				, @VALOROP7BX
				, @VALOROP8BX
				, @VALORINSSBX
				, @VALORIRRFBX
				, @VALORSESTSENATBX
				, @VALORDEVOLUCAOBX
				, @VALORNOTACREDITOBX
				, @VALORADIANTAMENTOBX
				, @VALORJUROSVENDORBX
				, @VALORRETENCOESBX
				, @VALORPERDAFINANCEIRABX
				, @VALORVINCULADO
				, @MODELOCONTABILIZACAO
				, @MODELOCONTABILIZACAOBAIXA
				, @VALORDESCONTODUPLICATA
				, @VALORDESCONTOACORDO
				, @VALORACRESCIMOACORDO
				, @STATUSORCAMENTO
				, @VALORDESCONTOPONTUALBX
				, @IDXCX
				, @IDTRANSACAO
				, @DATABAIXA
				, @VALORBAIXA
				--, @VALORINSS
				, @VALORIRRF
				--, @VALORSESTSENAT
				--, @VALORDEVOLUCAO
				, @VALORNOTACREDITO
				, @VALORNOTACREDITOADIANTAMENTO
				, @VALORJUROSVENDOR
				, @VALORRETENCOES
				, @VALORPERDAFINANCEIRA
				, @VALORJUROSACORDO
				--, @VALORDESCONTOACORDO
				--, @VALORACRESCIMOACORDO
				, @TIPOBAIXA
				, @STATUS
				, @DIFBAIXAPARCIAL
				, @TIPORETORNOBANCARIO
				, @ORIGEMVALORDESCONTO
				, @ORIGEMVALORJUROS
				, @ORIGEMVALORMULTA
				, @ORIGEMVALORCAP
				, @ORIGEMVALOROP1
				, @ORIGEMVALOROP2
				, @ORIGEMVALOROP3
				, @ORIGEMVALOROP4
				, @ORIGEMVALOROP5
				, @ORIGEMVALOROP6
				, @ORIGEMVALOROP7
				, @ORIGEMVALOROP8
				, @VALORDESCONTOPONTUAL
				, @IDBAIXA
				, @TIPO
				, @COMPENSADO
				, @RECONCILIADO
				--, @STATUSEXPORTACAO
				, @VALOR
				, @DATA
				, @CONTABIL
				, @ECHEQUE
				, @TIPOCUSTODIA
				, @LIBERACAOAUTORIZADA
				, @CODMOEDA
				, @SERIEDOCUMENTO
				, @CODAPLICACAO
				, @HISTORICO
				, @USUARIO
				, @DTIMPORT
END
close adiantamento_cursor
Deallocate adiantamento_cursor

